package edu.bu.cs575.processscheduler;

/**
 * TODO: Insert description here. (generated by dirtnap)
 */
public class ProcessRunQueueEntry {
  public final ProcessBurstRequest request;
  private int registeredTicks;
  private SchedulingAlgorithm queueType;
  
  public ProcessRunQueueEntry(ProcessBurstRequest request, SchedulingAlgorithm queueType) {
    this.request = request;
    this.queueType = queueType;
    this.registeredTicks = 0;
  }
  
  public void registerTick() {
    ++this.registeredTicks;
  }
  
  public boolean isBurstComplete() {
    return (this.registeredTicks == this.request.burstSize);
  }
}
