package edu.bu.cs575.processscheduler;

import java.util.HashMap;
import java.util.Map;

/**
 * TODO: Insert description here. (generated by dirtnap)
 */
public class ProcessBurstRequest {
  public final Process process;
  private Map<SchedulingAlgorithm, ProcessRunQueueEntry> requests;
  public final int enqueueuTime;
  public final int burstSize;
  public ProcessBurstRequest(Process process, int ticks, int burstSize) {
    this.process = process;
    this.enqueueuTime = ticks;
    this.burstSize = burstSize;
    this.requests = new HashMap<SchedulingAlgorithm, ProcessRunQueueEntry>();
  }
  public ProcessRunQueueEntry getRunQueueEntry(SchedulingAlgorithm queueType) {
    if (this.requests.containsKey(queueType)) {
      return this.requests.get(queueType);
    }
    ProcessRunQueueEntry result = new ProcessRunQueueEntry(this);
    this.requests.put(queueType, result);
    return result;
  }
}
