package edu.bu.cs342.p02;

import edu.bu.cs342.utilities.UserInput;

/**
 * TODO: Insert description here. (generated by dirtnap)
 */
public class EightQueens {

    private UserInput userInput;

    /**
     * 
     */
    public EightQueens() {
        this.userInput = new UserInput(System.in, System.out);
    }

    /**
     * @param args
     */
    public static void main(String[] args) {
        EightQueens self = new EightQueens();
        while (self.userInput.readBoolean("Solve an 8 Queens board", "Y", "n", true)) {
            Queen q = new Queen(self.getPosition());
            Chessboard board = new Chessboard(q);
            if (board.isSolved()) {
                System.out.printf("Solution for the board with queen at:  %s%n%n%s%n%n",
                        q.position, board);
            } else {
                System.out.printf("No Solution for the board with queen at:  %s%n", q.position);
            }
        }
    }

    /**
     * @return
     */
    private Position getPosition() {
        int rank = 0, file = 0;
        do {
            rank = this.userInput.readInteger(
                    "Enter starting rank (row) as an integer between 1 and 8", 1);
        } while (rank > 8);
        do {
            file = this.userInput.readInteger(
                    "Enter starting file (column) as an integer between 1 and 8", 1);
        } while (rank > 8);
        return new Position(rank, file);
    }

}
