package edu.bu.cs342.p02;

/**
 * TODO: Insert description here. (generated by dirtnap)
 */
public class IllegalPlacementException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    public IllegalPlacementException() {
        super();
    }
}
