package edu.bu.cs342.p02;

/**
 * TODO: Insert description here. (generated by dirtnap)
 */
public class IllegalPlacementException extends RuntimeException {

    /**
     * 
     */
    public IllegalPlacementException() {
        super();
    }
}
